# config.py

TICKERS = ["AAPL", "MSFT", "SPY"]

TOTAL_CAPITAL = 10.0
AI_CAPITAL = 5.0

MAX_POSITION_PCT = 0.20   # 20% per trade
DECISION_INTERVAL_MIN = 5
MAX_TRADES_PER_DAY = 5

MARKET_TIMEZONE = "US/Eastern"
